[package]
name = "promptly"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]

[dependencies]
failure = "0.1.2"
chrono = "0.3"
clap = "2.24"
git2 = "0.6"
hostname = "0.1"
time = "0.1"
users = "0.5.2"
