version: 2
jobs:
  test:
    working-directory: /promptly
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - promptly-test-{{ checksum "Cargo.toml" }}
            - promptly-test-
      - run:
          name: Prepare
          command: |
            rustup component add clippy-preview
            cargo clippy
            cargo build
            cargo build --release
      - save_cache:
          key: promptly-test-{{ checksum "Cargo.toml" }}
          paths:
            - /promptly/target
      - run:
          name: Clippy
          command: cargo clippy --all-targets --all-features -- -D warnings
      - run:
          name: 'Test Debug'
          command: cargo test
      - run:
          name: 'Test Release'
          command: cargo test --release
  
  # publish:
  #   working-directory: /promptly
  #   docker:
  #     - image: rust:latest
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - promptly-package-{{ checksum "Cargo.toml" }}
  #           - promptly-package-
  #     - run:
  #         name: Package
  #         command: cargo package
  #     - save_cache:
  #         key: promptly-package-{{ checksum "Cargo.toml" }}
  #         paths:
  #           - /promptly/target
  #     - run:
  #         name: Publish
  #         command: |
  #           cargo login <>
  #           cargo publish

workflows:
  version: 2
  test:
    jobs:
      - test
      # - publish:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: master