version: 2
jobs:
  test:
    working-directory: /promptly
    docker:
      - image: rust:latest
  steps:
    - checkout
    - restore_cache:
        keys:
          - promptly-{{ checksum "Cargo.toml" }}
          - promptly-
    - run:
        name: Prepare
        command: |
          rustup component add clippy-preview
          cargo clippy
          cargo build
          cargo build --release
    - save_cache:
        key: promptly-{{ checksum "Cargo.toml" }}
        paths:
          - /promptly/target
    # - run:
    #     name: Clippy
    #     command: cargo clippy --all-targets --all-features -- -D warnings
    # - run:
    #     name: 'Test Debug'
    #     command: cargo test
    # - run:
    #     name: 'Test Release'
    #     command: cargo test --release

workflows:
  version: 2
  test:
    jobs:
      - test